image: clojure:latest

stages:
  - test

test:
  stage: test
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.lein
    - echo $LEIN_SETTINGS > $CI_PROJECT_DIR/.lein/profiles.clj
  script:
    - lein test

ancient:
  stage: test
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.lein
    - echo $LEIN_SETTINGS > $CI_PROJECT_DIR/.lein/profiles.clj
  script:
    - lein ancient
  allow_failure: true

kibit:
  stage: test
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.lein
    - echo $LEIN_SETTINGS > $CI_PROJECT_DIR/.lein/profiles.clj
  script:
    - lein kibit
  allow_failure: true
