image: clojure:latest

stages:
  - lint
  - test

cljfmt:
  stage: lint
  script:
    - lein cljfmt check

kibit:
  stage: lint
  script:
    - lein kibit
  allow_failure: true

ancient:
  stage: test
  script:
    - lein ancient
  allow_failure: true

test:
  stage: test
  script:
    - lein test
