image: clojure:latest

stages:
  - test

test:
  stage: test
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.lein
    - echo pwd
    - cat "$LEIN_SETTINGS" > "$CI_PROJECT_DIR/.lein/profiles.clj"
    - cat "$CI_PROJECT_DIR/.lein/profiles.clj"
  script:
    - pwd
    - lein test

ancient:
  stage: test
  before_script:
    - mkdir -p "$CI_PROJECT_DIR/.lein"
    - cat "$LEIN_SETTINGS" > "$CI_PROJECT_DIR/.lein/profiles.clj"
  script:
    - echo $LEIN_SETTINGS
    - lein ancient
  allow_failure: true

kibit:
  stage: test
  before_script:
    - mkdir -p "$CI_PROJECT_DIR/.lein"
    - cat "$LEIN_SETTINGS" > "$CI_PROJECT_DIR/.lein/profiles.clj"
  script:
    - lein kibit
  allow_failure: true
