image: clojure:latest

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - lein cljfmt check

test:
  stage: test
  script:
    - lein test

ancient:
  stage: test
  script:
    - lein ancient
  allow_failure: true

kibit:
  stage: test
  script:
    - lein kibit
  allow_failure: true
