version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/cpo
    docker:
      - image: circleci/clojure:lein-2.9.3
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: cpo-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: cpo-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: ~/cpo/target/uberjar/clj-photo-org-0.0.8-SNAPSHOT-standalone.jar
          destination: clj-photo-org-0.0.8-SNAPSHOT-standalone.jar
destination: uberjar
